### ISSUE TITLE
Is it possible to edit a protected PDF with a "Validate" button?

### ISSUE THREAD

**Issue by garrett-gottlieb** [adobe/pdfservices-node-sdk-samples#13]
Is it possible to edit a protected PDF with a "Validate" button?

**Comment by KhushbooBaheti** [comment]
This SDK can be used as server side dependency, and cannot be used directly in frontend JS based applications

**Comment by garrett-gottlieb** [comment]
Hmm... what does that have to do with my question???

**Comment by pulkit-maheshwr** [comment]
@garrett-gottlieb : We are not able to fully understand your requirement. Would it be possible for you, elaborate more on this?

**Comment by namangupta2100** [comment]
Hi @garrett-gottlieb - Following up on your question. 
Could you please elaborate a little on your use case and requirement? 
We have a remove password functionality through which you can remove the password protection, edit the PDF and reapply the protection. Regarding the "Edit functionality", are you using a custom application where you are editing the PDFs?

**Comment by anubhav-mhjn** [comment]
Closing this issue.
@garrett-gottlieb Please feel free to re-open the issue in case of any further queries.
