### ISSUE TITLE
Newlines / Paragraphs are not supported in Word Template

### ISSUE THREAD

**Issue by nikhilunni511** [adobe/pdfservices-node-sdk-samples#18]
**@adobe/pdfservices-node-sdk** to create PDF from a dynamic word template does not support text with multiple paragraphs / new lines, it will be escaped and merged into a single string.

### Expected Behaviour
Hi, how are you ?

Hope you are doing good.

### Actual Behaviour
Hi, how are you ? Hope you are doing good.

**Comment by anubhav-mhjn** [comment]
Hi @nikhilunni511 
Thanks for reporting this. We are working on it and will be providing a provision to add text with newlines. Stay tuned. Will keep you posted on this.

**Comment by nikhilunni511** [comment]
Hi @anubhav-mhjn , when can we expect an update because it is used as one of the key features in our project.

**Comment by anubhav-mhjn** [comment]
Hi @nikhilunni511, we are actively working on it. It can be expected to be released before this year's end. We will keep you posted on this thread.
