### ISSUE TITLE
Permissions not actively loaded

### ISSUE THREAD

**Issue by code-jorge** [adobe/pdfservices-node-sdk-samples#21]
### Expected Behaviour

Setting the permissions in a PDF Protect operation should determine edit/copy/print permissions in the resulting PDF

### Actual Behaviour

Permissions are always set to:

```
"permissions": {
      "assistive_technology": true,
      "form_filling": false,
      "copying": false,
      "page_extraction": true,
      "document_assembly": false,
      "commenting": false,
      "printing": "none",
      "editing": false
    }
 ```

### Reproduce Scenario (including but not limited to)

I've merged this sample:
https://github.com/adobe/pdfservices-node-sdk-samples/blob/master/src/protectpdf/protect-pdf-with-owner-password.js
With this sample:
https://github.com/adobe/pdfservices-node-sdk-samples/blob/master/src/pdfproperties/pdf-properties-as-json.js

And the resulting PDF's properties indicate that permissions haven't been set correctly AFAIK

#### Platform and Version

Currently using 
"@adobe/pdfservices-node-sdk": "^2.1.0"
With
node.js v16.5.0

**Comment by anubhav-mhjn** [comment]
Hi @code-jorge , issues here should address problems in the samples for this repo. To raise any issues related to your custom code usage, please use our community forum for better tracking.

Link to the community forum: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK
