### ISSUE TITLE
Could you guys please support typescript? 

### ISSUE THREAD

**Issue by burtonator** [adobe/pdfservices-node-sdk-samples#22]
Feature request.. Please provide typescript types :)

**Comment by sfwhite** [comment]
+1 we're building integrations to your API in AWS using Typescript and not having the types to help keep developers from making dumb mistakes is slowing things down considerably.

**Comment by Anderman** [comment]
Typescript support can be generator with [tsc](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).
There at least one wrong jsdoc type. the method 'serviceAccountCredentialsBuilder()' should return 'ServiceAccountCredentialsBuilder;'

It is only a hour work to support typescript

**Comment by anubhav-mhjn** [comment]
Thanks @burtonator @Anderman for bringing this request up. Currently, this request is not in our roadmap. We would request you to use our community forum to detail out your requirements along with the use cases, for our Product Management and Tech Evangelist group to evaluate them further.

Link to the community forum: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.

Hope this helps.

**Comment by Anderman** [comment]
@burtonator @sfwhite I created a PR in DefinitilyTyped repro. You can review and test and approve it to speedup the PR. see the [review](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60884/files) link. Examples how to use can you find in the [testscript](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60884/files#diff-477fa3f63863878ccbc97157d1623f847f197e0e59fc0df89ab2f40902220f0e)

**Comment by Anderman** [comment]
for Typescript you can use `npm install --save @types/adobe__pdfservices-node-sdk`
