### ISSUE TITLE
Export jpeg and png to PDF

### ISSUE THREAD

**Issue by ducmaxime** [adobe/pdfservices-node-sdk-samples#24]
Do you planned to give the possibility to export an image (jpg, png) to a PDF ?

**Comment by anubhav-mhjn** [comment]
Hi @ducmaxime 
I am assuming that you want to create a PDF from an image (jpg, png).
If yes, we would suggest using the Create PDF Operation with the image/jpeg or image/png source file format.
More details at: https://opensource.adobe.com/pdfservices-node-sdk-samples/apidocs/latest/CreatePDFOperation.html

Please feel free to re-open the issue in case of any further queries.
