### ISSUE TITLE
Can we change our own templates ?

### ISSUE THREAD

**Issue by YugandharSarath** [adobe/pdfservices-node-sdk-samples#29]
Can we change for our own templates or only the sample files that are available in resources folder ??

**Comment by namangupta2100** [comment]
@YugandharSarath  - Thank you for your query. By templates, do you mean js files or input files being used in the sample code?
The sample code is to ease out the setup process for you. You can change it as per your own use case. Please feel free to configure and run the samples as per your needs and on your documents.
Hope this helps.

**Comment by anubhav-mhjn** [comment]
Closing this issue.
@YugandharSarath Please feel free to re-open the issue in case of any further queries.
