### ISSUE TITLE
Custom header, footer and page numbers

### ISSUE THREAD

**Issue by staticdreams** [adobe/pdfservices-node-sdk-samples#32]
I'm looking to generate a multipage document from a dynamic html file with custom header and custom footer (both should auto appear on all pages) which would also contain page current page number / total pages (e.g 2/10). Is this at all possible?

There is similar a [post in Adobe Community](https://community.adobe.com/t5/document-services-apis-discussions/how-to-set-header-footer-and-page-number-in-create-a-pdf-from-dynamic-html/m-p/12212611) but nobody ever answered the man in 11 months.

**Comment by anubhav-mhjn** [comment]
Hi @staticdreams , issues raised here should address problems in the samples for this repo. Closing this ticket. 

Adobe community forum will be the appropriate place for the same: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
