### ISSUE TITLE
@adobe/pdfservices-node-sdk depends on vulnerable versions of jsonwebtoken  <=8.5.1 (npm high severity vulnerability)

### ISSUE THREAD

**Issue by iamfaisalh** [adobe/pdfservices-node-sdk-samples#36]
### Reproduce Scenario (including but not limited to)

npm install @adobe/pdfservices-node-sdk

#### Platform and Version

Node v18.12.1

#### Logs taken while reproducing problem

jsonwebtoken  <=8.5.1
Severity: high
jsonwebtoken's insecure implementation of key retrieval function could lead to Forgeable Public/Private Tokens from RSA to HMAC - https://github.com/advisories/GHSA-hjrf-2m68-5959
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify() - https://github.com/advisories/GHSA-qwph-4952-7xr6
jsonwebtoken unrestricted key type could lead to legacy keys usage  - https://github.com/advisories/GHSA-8cf7-32gw-wr33
jsonwebtoken has insecure input validation in jwt.verify function - https://github.com/advisories/GHSA-27h2-hvpr-p74q
No fix available
node_modules/jsonwebtoken
  @adobe/pdfservices-node-sdk  *
  Depends on vulnerable versions of jsonwebtoken
  node_modules/@adobe/pdfservices-node-sdk

**Comment by vardhi** [comment]
Hi @iamfaisalh, we are working on its fix. Thanks!

**Comment by hitesh-kumar-mahour** [comment]
@iamfaisalh the issue has been fixed in the latest NodeJS SDK v3.2.0. Here is the [link](https://www.npmjs.com/package/@adobe/pdfservices-node-sdk?activeTab=versions) for your reference.
