### ISSUE TITLE
Where is the Node SDK repository?

### ISSUE THREAD

**Issue by nalloyd2** [adobe/pdfservices-node-sdk-samples#40]
Hi Adobe team. I'm getting started using the Node SDK for PDF to PPTX conversion but have found the OOTB methods involved in this process don't support my use case. I'm able to modify the package locally to do what I need, but ideally I'd like to fork the Node SDK and apply some modifications so I can use that as a project dependency for deployments. I can't seem to find the repo for this SDK anywhere. 

Could someone please point me to it?

**Comment by anubhav-mhjn** [comment]
Hi @nalloyd2 , thanks a lot for reaching out.

Unfortunately, the PDF Services NodeJS SDK code is not hosted on public code repos.

Please feel free to reach out to our [community forum](https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions) to discuss further on any such requirements.
