### ISSUE TITLE
how to parse scan pdf with Chinese？

### ISSUE THREAD

**Issue by Ontheroad123** [adobe/pdfservices-node-sdk-samples#41]
### Expected Behaviour
I parse scan pdf with Chinese, the result can't understand

#### Platform and Version
python-3.8.13

#### Sample Code that illustrates the problem
`
import logging
import os.path as osp
import os 
import re 

import PyPDF2
from PyPDF2 import PdfReader
from adobe.pdfservices.operation.auth.credentials import Credentials
from adobe.pdfservices.operation.client_config import ClientConfig
from adobe.pdfservices.operation.exception.exceptions import ServiceApiException, ServiceUsageException, SdkException
from adobe.pdfservices.operation.pdfops.options.extractpdf.extract_pdf_options import ExtractPDFOptions
from adobe.pdfservices.operation.pdfops.options.extractpdf.extract_element_type import ExtractElementType
from adobe.pdfservices.operation.execution_context import ExecutionContext
from adobe.pdfservices.operation.io.file_ref import FileRef
from adobe.pdfservices.operation.pdfops.extract_pdf_operation import ExtractPDFOperation
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))

def parse(pdfile, jsonfile, fp):
    try:
        # get base path.
        base_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        # Initial setup, create credentials instance.
        credentials = Credentials.service_account_credentials_builder() \
            .from_file(base_path + "/pdfservices-api-credentials.json") \
            .build()
        client_config = ClientConfig.builder().with_connect_timeout(10000).with_read_timeout(1000000)\
        .build()
        # Create an ExecutionContext using credentials and create a new operation instance.
        execution_context = ExecutionContext.create(credentials, client_config)
        extract_pdf_operation = ExtractPDFOperation.create_new()

        # Set operation input from a source file.
        source = FileRef.create_from_local_file(pdfile)
        print(source)
        extract_pdf_operation.set_input(source)

        # Build ExtractPDF options and set them into the operation
        extract_pdf_options: ExtractPDFOptions = ExtractPDFOptions.builder() \
            .with_element_to_extract(ExtractElementType.TEXT) \
            .build()
        extract_pdf_operation.set_options(extract_pdf_options)

        # Execute the operation.
        result: FileRef = extract_pdf_operation.execute(execution_context)

        # Save the result to the specified location.
        print(jsonfile)
        result.save_as(jsonfile)
        fp.write(pdfname+' success'+'\n')
    except (ServiceApiException, SdkException):
        logging.exception("Exception encountered while executing operation")
        fp.write(pdfname+' failed'+'\n')

pdfname = './test.pdf'
jsonname = './test.zip'
parse(pdfname, jsonname, fp)
`
#### Logs taken while reproducing problem
the json file can't encode.
[test.zip](https://github.com/adobe/pdfservices-node-sdk-samples/files/11475579/test.zip)

**Comment by varkumaradobe** [comment]
Hi @Ontheroad123 , issues raised here should address problems in the samples for this repo. Closing this ticket.

Adobe community forum will be the appropriate place for the same: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
